language: java
jdk:
  - oraclejdk8

services:
    - postgresql

env:
  global:
    - BUILD_TOOL=maven

before_script:
  - psql -c "create database catwatch;" -U postgres
  - psql -c "create database catwatch_test;" -U postgres
  - psql -c "create user cat1 with password 'cat1';" -U postgres

script:
  - ./build.sh
